apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  annotations:
    avp.kubernetes.io/path: "kv-v2/data/argocd"
    avp.kubernetes.io/path: "kv-v2/data/argocd2"
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
          - containerPort: 80
          env:
          - name: ANOTHER_ENV_VAR
            value: <envvar>
          - name: YET_ANOTHER_ENV_VAR
            value: <anotherkey>
          - name: MY_ENV_VAR
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: TOKEN
