apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    avp.kubernetes.io/path: "kv-v2/data/argocd"
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
  spec:
    containers:
    - name: nginx
      image: nginx:latest
      ports:
      - containerPort: 80
      env:
      - name: ANOTHER_ENV_VAR
        value: {{vault:secret/myapp/envvar}}
      - name: MY_ENV_VAR
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: TOKEN